apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind that we are creating
metadata:
  name: spring-boot-k8s-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: asbcbabu/docsample # Image that will be used to the containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080  # Thw port the container is running on the cluster
