apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-springboot
  template:
    metadata:
      labels:
        app: test-springboot
    spec:
      containers:
        - name: springboot
          image: asbcbabu/docsample:docsample
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: test-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: test-springboot